### ISSUE TITLE
Possible error in engine.cs ShiftDown() method

### ISSUE THREAD

**Issue by billtubbs** [jongallant/CarSimulator#1]
Possible error in the `engine.cs` code:

```
	public void ShiftUp() {
		CurrentGear++;
	}

	public void ShiftDown() {
		CurrentGear++;
	}
```

`ShiftDown()` should contain `CurrentGear--;` I assume?

**Comment by jongallant** [comment]
Yeah I wasn't done coding the manual transmission so that is actually code
that probably shouldn't even be there.

**Comment by billtubbs** [comment]
No worries.  I think you're right that any changes by these methods are currently redundant - they are over-written by the `UpdateAutomaticTransmission` method just after.  But you do have the 'a' and 'z' keys set up to shift gear so if anyone commented out the following line in `car.cs`, presumably it would go into manual transmission (I haven't tried it).

```
// Automatic transmission
Engine.UpdateAutomaticTransmission (Rigidbody2D);
```

**Comment by jongallant** [comment]
Yeah, exactly.  You would have to comment out that UpdateAutomaticTransmission in order to switch it to Manual Transmission.  

I updated the code in ShiftDown() as it was just wrong.  Thanks.
