### ISSUE TITLE
Car Movement Issue when car is placed on scene horizontally (with 90 or -90 z angle)

### ISSUE THREAD

**Issue by GraveRaveDave** [jongallant/CarSimulator#3]
Hi! Awesome simulation model, but right now i've encountered an issue wich may be interesting for you.
When i rotated player controlled car on scene to 90 angle car movement bugged out. When i press 'right' it starts to slide to the left sometimes with fantastic velocities (>10000 kph). the closer car to horizontal position on scene (90 or -90 degrees .z) the more noticable this effect is

*currently i don't know how to fix this, but if i find a way i'll tell you asap

**Comment by GraveRaveDave** [comment]
well, think i've located the problem
i guess it's in the void Init() {} function in 'AxleFront.DistanceToCG =' section

	void Init() {

		Velocity = Vector2.zero;
		AbsoluteVelocity = 0;

        // Dimensions, ---> HERE <----
        AxleFront.DistanceToCG = Mathf.Abs(CenterOfGravity.transform.position.y - AxleFront.transform.Find("Axle").transform.position.y);
        AxleRear.DistanceToCG = Mathf.Abs(CenterOfGravity.transform.position.y - AxleRear.transform.Find("Axle").transform.position.y);

        /*When i swapped the code above with commented one i've recreated the same problem for the vertical initial position of the car, but when i placed car horizontally on scene with commented code it worked fine, just as above code did with vertical placement before (i think). i just swapped all the '.y' with '.x' now i think it's time to think about universal solution for any initial position of the car, i'm kinda noob and still figuring out what this exact code does actually, so it might take some time
*/

        //AxleFront.DistanceToCG = Mathf.Abs(CenterOfGravity.transform.position.x - AxleFront.transform.Find("Axle").transform.position.x);
        //AxleRear.DistanceToCG = Mathf.Abs(CenterOfGravity.transform.position.x - AxleRear.transform.Find("Axle").transform.position.x);

        // Extend the calculations past actual car dimensions for better simulation
        AxleFront.DistanceToCG *= AxleDistanceCorrection;
		AxleRear.DistanceToCG *= AxleDistanceCorrection;
			
		WheelBase = AxleFront.DistanceToCG + AxleRear.DistanceToCG;
		Inertia = Rigidbody2D.mass * InertiaScale;

		// Set starting angle of car
		Rigidbody2D.rotation = transform.rotation.eulerAngles.z;
		HeadingAngle = (Rigidbody2D.rotation + 90) * Mathf.Deg2Rad;
//        HeadingAngle = (Rigidbody2D.rotation) * Mathf.Deg2Rad;
    }

**Comment by GraveRaveDave** [comment]
Okay) think i got it

in order to fix the problem i replaced this:
        AxleFront.DistanceToCG = Mathf.Abs(CenterOfGravity.transform.position.y - AxleFront.transform.Find("Axle").transform.position.y);
        AxleRear.DistanceToCG = Mathf.Abs(CenterOfGravity.transform.position.y - AxleRear.transform.Find("Axle").transform.position.y);

with this: 
        AxleFront.DistanceToCG = Vector3.Distance(CenterOfGravity.transform.position, AxleFront.transform.Find("Axle").transform.position);
        AxleRear.DistanceToCG = Vector3.Distance(CenterOfGravity.transform.position, AxleRear.transform.Find("Axle").transform.position);

and also this: 
TrackWidth = Mathf.Abs (AxleRear.TireLeft.transform.position.x - AxleRear.TireRight.transform.position.x);

with this:
TrackWidth = Vector3.Distance(AxleRear.TireLeft.transform.position, AxleRear.TireRight.transform.position);

**You did absolute awesome job on this simulation, it looks and feels fantastic, good luck and have a nice time!!!

**Comment by GraveRaveDave** [comment]
thank you for sharing your work!

**Comment by tetreum** [comment]
@GraveRaveDave if your changes fix the problem and code still works under normal conditions, why don't you send a pull request with your changes? So @jongallant can easily merge them :)
