### ISSUE TITLE
brakes doubt

### ISSUE THREAD

**Issue by Toku11** [jongallant/CarSimulator#6]
What's the difference between Brake and eBrake, because Brake is always 0, in fact you're printing Brake, and it will be always 0, you should print ebrake instead right?

**Comment by jongallant** [comment]
You are right.  Brake is currently not used.  You could implement it.  
I had changed it to force the car into reverse instead when pressing the down arrow.

**Comment by Toku11** [comment]
ok, in the weight transfer section, why the transferY is not divided by Gravity?, instead of that there is a wighttransfer constant of 0.35

**Comment by jongallant** [comment]
Gravity would also be constant.  Feel free to alter the model and see if
you can improve on it.
