### ISSUE TITLE
skidmarks problem

### ISSUE THREAD

**Issue by BylemTu** [jongallant/CarSimulator#8]
Hello, sorry for my not so perfect English. Every new skidmark is like teleporting to us from position 0.
![image](https://user-images.githubusercontent.com/45637619/93686016-c2a67400-fab3-11ea-9f5d-af8b2045f39d.png)

**Comment by sofielafee** [comment]
this is due to the position of the skidmark object updated after creation, I've fixed it in a pull request/fork
